### ISSUE TITLE
~/.config/kitchen-qemu/xenial.qcow2': No such file or directory

### ISSUE THREAD

**Issue by bitphage** [esmil/kitchen-qemu-images#1]
I tried to build a xenial image with no success. Seems like no one created ~/.config/kitchen-qemu/xenial.qcow2

```
% make xenial                             
kitchen converge xenial-default
-----> Starting Kitchen (v1.15.0)
-----> Creating <xenial-default>...
       KVM enabled.
       Spawning QEMU..
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <xenial-default>.  Please see .kitchen/logs/xenial-default.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

```

I, [2017-02-03T17:48:19.192429 #824390]  INFO -- xenial-default: -----> Creating <xenial-default>...
I, [2017-02-03T17:48:19.192763 #824390]  INFO -- xenial-default: KVM enabled.
I, [2017-02-03T17:48:19.193209 #824390]  INFO -- xenial-default: Spawning QEMU..
E, [2017-02-03T17:48:19.270180 #824390] ERROR -- xenial-default: Create failed on instance <xenial-default>.
E, [2017-02-03T17:48:19.270306 #824390] ERROR -- xenial-default: ------Exception-------
E, [2017-02-03T17:48:19.270332 #824390] ERROR -- xenial-default: Class: Kitchen::ActionFailed
E, [2017-02-03T17:48:19.270350 #824390] ERROR -- xenial-default: Message: qemu-system-x86_64: -drive if=none,id=drive0,snapshot=on,discard=unmap,file=/home/vvk/.config/kitchen-qemu/xenial.qcow2: Could not open '/home/vvk/.config/kitchen-qemu/xenial.qcow2': No such file or directory
E, [2017-02-03T17:48:19.270367 #824390] ERROR -- xenial-default: ----------------------
E, [2017-02-03T17:48:19.270408 #824390] ERROR -- xenial-default: ------Backtrace-------
E, [2017-02-03T17:48:19.270436 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/kitchen-qemu-0.2.7/lib/kitchen/driver/qemu.rb:266:in `create'
E, [2017-02-03T17:48:19.270456 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-02-03T17:48:19.270473 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-02-03T17:48:19.270489 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-02-03T17:48:19.270506 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-02-03T17:48:19.270522 #824390] ERROR -- xenial-default: /home/vvk/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-02-03T17:48:19.270539 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-02-03T17:48:19.270556 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-02-03T17:48:19.270572 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-02-03T17:48:19.270588 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-02-03T17:48:19.270611 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-02-03T17:48:19.270643 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-02-03T17:48:19.270665 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/instance.rb:135:in `converge'
E, [2017-02-03T17:48:19.270682 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-02-03T17:48:19.270698 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-02-03T17:48:19.270715 #824390] ERROR -- xenial-default: /home/vvk/.rvm/gems/ruby-2.3.0/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-02-03T17:48:19.270745 #824390] ERROR -- xenial-default: ----End Backtrace-----
```

**Comment by esmil** [comment]
Yeah, you have a chicken-and-egg problem. You need to first download a xenial image from here:
https://esmil.dk/kitchen-qemu/
Eg.
```sh
mkdir -p ~/config/kitchen-qemu/
curl 'https://esmil.dk/kitchen-qemu/xenial.qcow2.xz' | xz -cd > ~/config/kitchen-qemu/xenial.qcow2
```

**Comment by bitphage** [comment]
Thanks, I thought it should create an image from scratch.
